apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-{{ .Values.service.selector }}
  namespace: {{ .Values.namespace }}
  labels:
    app: eks-app
    version: {{ .Values.service.selector }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eks-app
      version: {{ .Values.service.selector }}
  template:
    metadata:
      labels:
        app: eks-app
        version: {{ .Values.service.selector }}
    spec:
      containers:
        - name: eks-app
          image: "{{ .Values.image.imageName }}:{{ if eq .Values.service.selector \"blue\" }}{{ .Values.image.tagBlue }}{{ else }}{{ .Values.image.tagGreen }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
