apiVersion: v1
kind: Service
metadata:
  name: {{ include "blue-green-eks-app.fullname" . }}-{{ .Values.color }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "blue-green-eks-app.name" . }}
    color: {{ .Values.color }}
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}

