namespace: dev

image:
  imageName: IMAGE_PLACEHOLDER
  tagBlue: "1.0.0"
  tagGreen: "1.0.1"
  pullPolicy: IfNotPresent

replicaCount: 2

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

service:
  name: my-app-svc
  port: 80
  targetPort: 8501
  selector: blue # or green

ingress:
  enabled: true
  className: alb
  host: eksapp-divya.growexx.com
  path: /
